# Generated by Django 3.0.1 on 2019-12-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(help_text='150x150px', upload_to='blog/static/media', verbose_name='Your Photo'),
        ),
    ]
