# Generated by Django 3.0.1 on 2019-12-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191231_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='blog/static/media', verbose_name='Your Photo'),
        ),
    ]
