# Generated by Django 3.0.1 on 2020-01-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191231_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/media/'),
        ),
    ]
