# Generated by Django 3.0.1 on 2020-01-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200105_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='count',
            new_name='count_of_views',
        ),
    ]
