# Generated by Django 3.0.1 on 2020-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200124_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
