# Generated by Django 3.0.1 on 2020-01-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
