# Generated by Django 3.0.1 on 2020-02-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0029_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='post',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
