# Generated by Django 3.0.1 on 2020-02-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200204_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
