# Generated by Django 3.0.1 on 2020-02-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_remove_survey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='blog.Post'),
        ),
    ]
