# Generated by Django 3.0.1 on 2020-02-05 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200205_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='survey',
        ),
        migrations.AddField(
            model_name='variant',
            name='Type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='blog.Post'),
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
