# Generated by Django 3.0.1 on 2020-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20200205_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.AddField(
            model_name='post',
            name='surveysquestion',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
