# Generated by Django 3.0.1 on 2020-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20200205_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='surveysquestion',
            field=models.CharField(max_length=200),
        ),
    ]
