# Generated by Django 3.0.1 on 2020-02-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20200205_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='surveysquestion',
            new_name='question',
        ),
    ]
