# Generated by Django 3.0.1 on 2020-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_remove_post_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
