# Generated by Django 3.0.1 on 2020-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20200213_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo_of_user',
            field=models.ImageField(blank=True, upload_to='blog/static/media/users/'),
        ),
    ]
