# Generated by Django 3.0.1 on 2020-02-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_comment_photo_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo_of_user',
            field=models.ImageField(blank=True, upload_to='blog/static/media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog/static/media/'),
        ),
    ]
