# Generated by Django 3.0.1 on 2020-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20200215_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='darktheme',
            field=models.BooleanField(default=False),
        ),
    ]
