# Generated by Django 3.0.1 on 2020-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inpostphotos',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/media/'),
        ),
    ]
