# Generated by Django 3.0.1 on 2020-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_ad_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='period_of_publication',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
