# Generated by Django 3.0.1 on 2020-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20200305_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='period_of_publication',
        ),
        migrations.AddField(
            model_name='ad',
            name='remove_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
