# Generated by Django 3.0.1 on 2020-03-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_auto_20200305_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
