# Generated by Django 3.0.1 on 2020-04-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_text',
        ),
    ]
