# Generated by Django 3.0.8 on 2020-07-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_remove_post_cover_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='typeofvote',
        ),
        migrations.AddField(
            model_name='post',
            name='survey_is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_vote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
