# Generated by Django 3.0.8 on 2020-08-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20200811_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='inpostphotos',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='blog.Image'),
        ),
    ]
