# Generated by Django 3.0.8 on 2020-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20200813_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='by_administration',
            field=models.BooleanField(default=False),
        ),
    ]
