# Generated by Django 3.0.8 on 2020-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_comment_by_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
