# Generated by Django 3.0.8 on 2020-08-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
