# Generated by Django 3.0.8 on 2020-09-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar_Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('cover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_image', to='blog.Image')),
            ],
        ),
    ]
