# Generated by Django 3.0.8 on 2020-09-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_sidebar_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar_ad',
            name='cover',
        ),
        migrations.AddField(
            model_name='sidebar_ad',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_image', to='blog.Image'),
        ),
        migrations.AlterField(
            model_name='sidebar_ad',
            name='link',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sidebar_ad',
            name='text',
            field=models.CharField(default='Salut', max_length=50),
        ),
    ]
