# Generated by Django 3.0.8 on 2020-09-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_auto_20200902_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar_ad',
            name='link',
            field=models.TextField(default=None, null=True),
        ),
    ]
