# Generated by Django 3.0.8 on 2020-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0079_auto_20200902_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sidebar_ad',
            name='text',
            field=models.CharField(default='Salut!', max_length=50),
        ),
    ]
