# Generated by Django 3.0.8 on 2020-09-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0080_auto_20200903_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sidebar_Ad',
        ),
    ]
