# Generated by Django 3.0.8 on 2020-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0082_ad_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_block',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
