# Generated by Django 3.0.8 on 2020-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0083_ad_block_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_block',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
