# Generated by Django 3.0.8 on 2020-09-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0084_auto_20200911_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
