# Generated by Django 3.0.8 on 2020-09-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0086_auto_20200913_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspapper',
            old_name='image',
            new_name='pdf',
        ),
    ]
