# Generated by Django 3.0.8 on 2020-12-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0088_remove_comment_photo_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='block_comments',
            field=models.BooleanField(default=False),
        ),
    ]
