# Generated by Django 3.0.8 on 2020-12-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0089_post_block_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_block',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
